name: Basic library (ipfs_client) build
on:
  pull_request:
jobs:
  test:
    name: Run Tests & Publish Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes cmake ninja-build lcov binutils
      - name: Configure
        shell: bash
        run: |
          mkdir build
          cmake \
            -G Ninja \
            -S . \
            -B build \
            -D CMAKE_BUILD_TYPE=Debug
      - name: Run Tests
        shell: bash
        run: cmake --build build --config Debug --target cov
      - name: Upload coverage reports to Codecov.com
        uses: codecov/codecov-action@v3
        with:
          files: build/library/cov.info
  build:
    name: ${{ matrix.config.name }}
    needs: test
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "macOS",
              os: macos-latest,
              build_type: "Release",
              cc: "clang",
              cxx: "clang++",
              generators: "Ninja"
            }
          - {
              name: "Ubuntu",
              os: ubuntu-latest,
              build_type: "Release",
              cc: "gcc",
              cxx: "g++",
              generators: "Ninja"
            }
          - {
              name: "Ubuntu-Debug",
              os: ubuntu-latest,
              build_type: "Debug",
              cc: "gcc",
              cxx: "g++",
              generators: "Ninja"
            }
          - {
              name: "Windows-MSVC",
              os: windows-latest,
              build_type: "Release",
              cc: "cl",
              cxx: "cl",
              generators: "Visual Studio 17 2022"
            }
    steps:
      - uses: actions/checkout@v3
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          pwd
          git status
          which python3 
          python3 --version
      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install --yes cmake ninja-build
          ninja --version
          cmake --version
          g++ --version
      - name: Install dependencies on macos
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install cmake ninja
          ninja --version
          cmake --version
      - name: Install dependencies on Windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install ninja cmake
          python3 -m pip install --upgrade pip
          python3 -m pip install conan
          conan profile detect
          Copy-Item ".\.github\msvc.profile" -Destination "C:\Users\runneradmin\.conan2\profiles\default"
          ninja --version
          cmake --version
          conan --version
      - name: Configure
        shell: bash
        run: |
          mkdir build
          mkdir ipfs-client-dev
          cmake \
            -G "${{ matrix.config.generators }}" \
            -S . \
            -B build \
            -D CMAKE_INSTALL_PREFIX=`pwd`/ipfs-client-dev \
            -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
      - name: Build
        shell: bash
        run: cmake --build build --config ${{ matrix.config.build_type }} --target package
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: static_library.${{ matrix.config.os }}
          path: build/library/libipfs_client.a # TODO .lib naming on Windows
          retention-days: 1
